### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by Thijs5** [saivarunk/vue-simple-upload#2]
When installing in a Vue 2.2.2 project, I get the following error when trying to use the plugin:

```ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-simple-upload/dist/FileUpload.vue
Module build failed: Error: Couldn't find preset "es2015" relative to directory \\node_modules\\vue-simple-upload"
    at \node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (\node_modules\babel-loader\lib\index.js:46:20)
    at Object.module.exports (\node_modules\babel-loader\lib\index.js:155:20)
 @ ./~/vue-simple-upload/dist/FileUpload.vue 3:2-94
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/BnpBlacklist.vue
 @ ./src/components/pages/BnpBlacklist.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js```

**Comment by saivarunk** [comment]
Issue resolved with version 0.1.6
